sudo: required
language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ruby ruby-dev rubygems-integration build-essential rpm
  - gem install --no-document fpm
  - sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
  - wget http://www.us.apache.org/dist/thrift/0.12.0/thrift-0.12.0.tar.gz
  - tar xfz thrift-0.12.0.tar.gz
  - cd thrift-0.12.0 && ./configure --enable-libs=no  && sudo make install
script:
  - cd $TRAVIS_BUILD_DIR && ./build.sh
